name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Se você estiver usando submódulos no Git
          fetch-depth: 0

      - name: Install Zola
        run: |
          curl -L https://github.com/getzola/zola/releases/download/v0.17.1/zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz --output zola.tar.gz
          tar -xzf zola.tar.gz
          mv zola /usr/local/bin/zola

      - name: Build Zola site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
